apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotification-deployment
  labels:
    app: gotification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotification
  template:
    metadata:
      labels:
        app: gotification
    spec:
      containers:
        - name: gotification
          image: cluster:30500/gotification
          ports:
            - containerPort: 8080
      hostNetwork: true
      dnsPolicy: ClusterFirst