apiVersion: v1
kind: Pod
metadata:
  name: gotification
  labels:
    app: gotification
spec:
  containers:
    - name: gotification
      image: cluster:30500/gotification
      ports:
        - containerPort: 8080
  hostNetwork: true
  dnsPolicy: ClusterFirst