apiVersion: v1
kind: Service
metadata:
  name: gotify-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31111
  selector:
    app: gotify
